###
GET https://demo.duendesoftware.com/api/test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkMxNkFDOUJERThBNUEwRTlFNUEwRTFFNUFGMzA2QUExIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2RlbW8uZHVlbmRlc29mdHdhcmUuY29tIiwibmJmIjoxNjYyODE4OTY0LCJpYXQiOjE2NjI4MTg5NjQsImV4cCI6MTY2MjgyMjU2NCwiYXVkIjoiYXBpIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJpbnRlcmFjdGl2ZS5wdWJsaWMiLCJzdWIiOiIxIiwiYXV0aF90aW1lIjoxNjYyODE4Njk4LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJBbGljZSBTbWl0aCIsImVtYWlsIjoiQWxpY2VTbWl0aEBlbWFpbC5jb20iLCJzaWQiOiI2MDM3NjIyNTM4OEM4NDhBMzhBMzMxMzExRTUzM0Y5QiIsImp0aSI6IjdCNEZGOUU3QTE0MzcyNUIxMjFGMDYxNDY4RUYxNEI5In0.jpIVzSxQ_Bd4XAk9ihh_7LVyuIm_nbBbqfwbPFhfA4g8-KOG-0ZudIzIXlP6tGP4Fj3GwB56FltYGNAm_zItyzVA1j_9lFd4o0Gh1k_iykFp6BkJCpogGeeDOzC3bxCrvOGMP9Vxi_ZqzgT0dBjssL1Br7NsJJ53Ire5Sc___SyyR4kTkzIHU-vkDKN0KVcfOZ2Sgo7wLUxDXrvsv2qB9wx44shGjQh4VcKWPslylviXwNh0aQgIVFkUJmuVJLFbr1SnjrOmH1ZaDv7-eQLTkvXb8H2oM8oByjBsyU6AoBJ7QRIzbGFQv-9A2PQhWa3WDYj4WfZ9Rxe5ydFeKp6EjA